<?php

/**
	
	@class  model 
	@param	(mixed) id/ide or null
	@param	(string) aql/model_name/ or null
	@param 	(array) config options

**/

if (!class_exists('ModelArrayObject')) {
	include 'class.ModelArrayObject.php';
}

class Model implements ArrayAccess {

	public static $_metadata = array();

	const E_READ_ONLY = 'The site is currently in "read only" mode. Changes have not been saved. Try again later.';
	const E_NO_METHOD_EXISTS = 'Cannot call a method that does not exist.';
	const E_METHOD_NOT_CALLABLE = 'This method is not callable.';
	const E_PROPERTY_DOES_NOT_EXIST = 'Property [%s] does not exist in this model.';
	const E_METHOD_ALREADY_DEFINED = 'Method [%s] is already defined in this model.';

	public $_aql = null; // store actual .aql file when found or input aql
	public $_token = null; // used to authorize updates
	public $_aql_array = array(); // generated by $_aql
	public $_data = array(); // all stored data, corresponds to each of $_properties
	public $_do_set = false;
	public $_errors = array(); // return errors
	public $_id; // identifier set in loadDB if successsful
	public $_ignore = array(); // tables (array) , models (array) , subs (array)
	public $_objects = array(); // names of objects
	public $_methods = array(); // array of methods added via addMethod
	public $_model_name = null; // from classname
	public $_primary_table; // primary table name of the model. 
	public $_properties = array(); // array of fields generated by the model
	public $_required_fields = array(); // 'field' => 'Name'
	public $_return = array();

	// used with $model::$mod_time to see if the object is out of date
	public $_cached_time = null;

	// these are configuration properties, that can be set in the model __cosntruct method $config param
	protected $_aql_set_in_constructor = false;
	protected $_use_token_validation = true;
	protected $_refresh_sub_models = true;
	protected $_is_inner_save = false; // for when saving a sub model

	// if true, the save will return after_save() without saving.
	public $_abort_save = false; 

/**

	@function  		__construct
	@param 			(identifier) 
	@param 			(mixed) set aql for this model (if this is not a subclass)
	@param 			(mixed) if true we're loading from DB and writing to cache
	@param 			(array) configuration options

	CONSTRUCTOR ACCEPTS ARGUMENTS IN A VARIETY OF WAYS:

	$o = new artist($id);
	$o = new artist($id, $conf); 			// maps to new artist($id, null, false, $conf);
	$o = new artist($id, true); 			// maps to new artist($id, null, true);
	$o = new artist($id, true, $conf);		// maps to new artist($id, null, true, $conf);
	$o = new Model($id, $artist_aql, $conf);// maps to new model($id, $artist_aql, false, $conf);

**/
	public function __construct($id = null, $aql = null, $do_set = false, $config = array()) {
		
		# map arguments to correct vars
		list($aql, $do_set, $config) = $this->mapConstructArgs($aql, $do_set, $config);
		
		# initialize this model
		$this->_model_name = get_class($this);
		$this->_getModelAql($aql)->makeProperties();

		# set if we're refreshing it
		$this->_do_set = ($do_set || $_GET['refresh']);
		
		# set configuration options for 
		$this->setConfig($config);

		# load from DB if $id is set proper, otherwise throw Exception
		$this->checkConstructorID($id, $do_set);
		
		# run construct hook
		$this->construct();
	} 


	/*
		checks for a proper identifier, loads object if set
	*/
	protected function checkConstructorID($id = null, $set = false) {
		if (!$id) return;
		$e = 'The model __construct method does not support %s as a first argument. '
		   . 'Only: null|false|numeric|IDE';
		if (!is_string($id) && !is_numeric($id)) {
			throw new Exception(sprintf($e, gettype($id)));
		}
		$this->loadDB($id, $set);
		$this->_token = $this->getToken();
	}


	/*
		maps constructor arguments to a standard format by type
	*/
	protected function mapConstructArgs($aql = null, $do_set = false, $config = array()) {
		
		if (is_array($do_set)) {
			$config = $do_set;
			$do_set = false;
		}

		if (is_array($aql)) {
			$config = $aql;
			$aql = null;
		} else if (is_bool($aql)) {
			$do_set = $aql;
			$aql = null;
		}

		# return fixed and uniform arguments
		return array($aql, $do_set, $config);
	}

	# so as to not use method exists
	public function construct() { return $this; }

	public function __call($method, $params) {
		if (!$this->methodExists($method)) throw new Exception(self::E_NO_METHOD_EXISTS);
		if (!is_callable($this->_methods[$method])) throw new Exception(self::E_METHOD_NOT_CALLABLE);
		return call_user_func_array($this->_methods[$method], $params);
	}

	/*
		if this model is called as a function, return dataToArray();
		ex: $o = new artist;
			$o(); # equivalent to $o->dataToArray();
	*/
	public function __invoke() {
		return $this->dataToArray();
	}


/**
	
	@function	__get
	@return		(mixed)
	@param		(string)

**/
	final public function __get($name) {
		return ($this->propertyExists($name))
			? $this->_getField($name)
			: null;
	}

	protected function _getField($name) {
		return $this->_data[$name];
	}

/**
	
	@function	__set
	@return		(model)
	@param		(string)
	@param		(mixed)

**/
	public function __set($name, $value) {
		
		# check to see if this is a valid property or IDE
		$is_ide = preg_match('/_ide$/', $name);
		if (!$this->propertyExists($name) && !$is_ide) {
			$this->_errors[] = sprintf(self::E_PROPERTY_DOES_NOT_EXIST, $name);
			return $this;
		}

		# if this is an IDE we add it as a property to the object
		if (!$this->propertyExists($name)) $this->addProperty($name);

		# cast to array or to modelArrayObject as necessary
		$value = $this->prepSetValue($value);

		$this->_data[$name] = $value;

		#if is IDE, add as an ID as well
		if ($is_ide) {
			$key = aql::get_decrypt_key($name); # decrypt ide
			$n_name = substr($name, 0, -1); 	# remove e (from ide)
			$this->_data[$n_name] = decrypt($value, $key); 
		}

		return $this;
	}


	/*
		cast value to array if it is a stdClass
		to arrayobject if it is an array
		otherwise return it as it was
	*/
	private function prepSetValue($val) {
		if (!is_array($val) && !is_object($val)) return $val;
		if (is_array($val)) return self::toArrayObject($val);
		if (get_class($val) == 'stdClass') return (array) $val;
		return $val;
	}

	/*
		echoing a model returns $model->getID();
	*/
	public function __toString() {
		return $this->getID();
	}

	/*
		save will never go through, it will go through validation
		and return_save if no errors
	*/
	public function abortSave() {
		$this->_abort_save = true;
	}


	/*
		merge to the required fields array
	*/
	public function addRequiredFields($arr = array()) {
		if (!is_assoc($arr)) {
			throw new Exception('Model::addRequiredFields expects an associative array with field => return name.');
		}
		$this->_required_fields = array_merge($this->_required_fields, $arr);
	}

	/*
		add any number of properties to the object
	*/
	public function addProperty() {
		$num_args = func_num_args();
		$args = func_get_args();
		for ($i = 0; $i < $num_args; $i++) {
			$this->_properties[$args[$i]] = true;
		}
		return $this;
	}


	/*
		alias for Model::addProperty()
	*/
	public function addProperties() {
		$args = func_get_args();
		call_user_func_array(array($this, 'addProperty'), $args);
		return $this;
	}

	/*
		add a method to this model
		usage:
			$model->addMethod('testing', function($arg) use($model) {
				// body
			});
			$model->testing($somearg);
		@return $this
		@param (string) $name
		@param (callback) $fn
	*/
	public function addMethod($name, $fn) {
		
		if ($this->methodExists($name)) {
			throw new Exception(sprintf(self::E_METHOD_ALREADY_DEFINED, $name));
		}

		$this->_methods[$name] = $fn;
		return $this;
	}

	/*
		@return (bool)
		@param (string) $name
	*/
	public function methodExists($name) {
		return (method_exists($this, $name)) 
			?: array_key_exists($name, $this->_methods);
	}


	/*
		@return array of mapped sub objects
		@param (string) object name
		@param (callback)
		@param (bool) $skip_id_filter
		
		plural subobject specific "array_map", because these are not arrays
		if the model has [sub_model]s
		$model->mapSubObjects('sub_model', $callback)

	*/
	public function mapSubObjects($name, $fn = null, $skip_id_filter = false) {
		
		if (!$this->isPluralObject($name)) {
			throw new Exception('mapSubObjects expects a valid plural object param.');
		}

		$re = array();
		foreach ($this->$name as $o) {
			if (!$skip_id_filter && !$o->getID()) continue;
			$re[] = ($fn) ? $fn($o) : $o;
		}
		return $re;
	}


/**

	@function 	after_fail
	@return		(null)
	@param		(array) -- the save array

**/

	public function after_fail($arr = array()) {
		return array_merge(array(
			'status' => 'Error',
			'errors' => $this->_errors,
			'data' => $this->dataToArray(true)
		), $this->_return);
	}

/**

	@function	after_save
	@return		(null)
	@param		(array) -- save array

**/

	public function after_save($arr = array()) {
		return array_merge(array(
			'status' => 'OK',
			'data' => $this->dataToArray(true),
			'_token' => $this->getToken()
		), $this->_return);
	}

	public function hasRequiredFields() {
		return (bool) (count($this->getRequiredFields() > 0));
	}

	public function getRequiredFields() {
		return array_keys($this->_required_fields);
	}

	public function getID() {
		$field = $this->_primary_table.'_id';
		$field_ide = $field. 'e' ;
		return $this->{$field} = ($this->{$field}) ?: ($this->{$field_ide}) 
				? decrypt($this->{$field_ide}, $this->_primary_table)
				: null;
	}

	public function getIDE() {
		$field = $this->_primary_table.'_id';
		$field_ide = $field.'e';
		return ($this->{$field_ide}) ?: ($this->{$field})
			? encrypt($this->{$field}, $this->_primary_table)
			: null;
	}

/**

	@function 	getIDByRequiredFields()
	@return 	(model)
	@param 		(null)

	Uses required fields to fetch the identifier of the object if it is not set
	Should generally be used in postValidate() for a uniqueness constraint on the 
	required fields

**/

	public function getIDByRequiredFields() {

		# if there are errors | have ID | no required fields return 
		if ($this->_errors || $this->getID() || !$this->hasRequiredFields()) {
			return $this;
		}

		# set up
		$where = array();
		$clause = array('limit' => 1, 'where' => &$where);
		$aql = sprintf('%s { }', $this->getPrimaryTable());
		$key = $this->getPrimaryTable() . '_id';

		# make where
		foreach ($this->getRequiredFields() as $f) {
			$where[] = sprintf("%s = '%s'", $f, $this->{$f});
		}

		$rs = aql::select($aql, $clause);
		$this->{$key} = ($rs[0][$key]) ?: $this->{$key};
		$this->_token = ($this->_token) ?: $this->getToken();

		return $this;
	}

/**

	@function 	preFetchRequiredFields
	@param 		(null)
	@return 	model object

	Use to repopulate required fields from the database on save, only sets them if they are empty.
	Must be called within a model. Best to call this in preValidate();

**/

	public function preFetchRequiredFields($id = null) {
		$id = ($id) ?: $this->getID();
		if (!$id) return $this;
		
		$keys = $this->getRequiredFields();
		
		$continue = false;
		foreach ($keys as $f) {
			if (!$this->fieldIsSet($f)) {
				$continue = true;
				break;
			}
		}

		# return if all required fields are already set
		if (!$continue) return $this;

		# get data
		$r = aql::profile($this->getStoredAqlArray(), $id);
		if ($r) foreach ($keys as $f) {
			if (!$this->fieldIsSet($f)) $this->_data[$f] = $r[$f];	
		}

		return $this;
	}

/**

	@function 	dataToArray
	@return		(array)
	@param		(null)

**/

	public function dataToArray($hide_ids = false) {
		$return = array();
		if (!$arr) $arr = $this->_data;
		foreach ($arr as $k => $v) {
			if ($this->_objects[$k] === 'plural') {
				foreach ($v as $i => $o) {
					if (self::isModelClass($o)) $return[$k][$i] = $o->dataToArray($hide_ids);
				}
			} else if ($this->_objects[$k] && get_class($v) != 'ModelArrayObject') {
				$return[$k] = $v->dataToArray($hide_ids);
			} else if (is_object($v) && get_class($v) == 'ModelArrayObject') {
				$return[$k] = self::dataToArraySubQuery($v);
			} else {
				$is_id = (substr($k, -3) == '_id');
				if (!$is_id || !$hide_ids) {
					$return[$k] = $v;
				}
			}
		}
		unset($arr);
		return $return;
	}

	public function dataToArraySubQuery($arr = array(), $hide_ids = false) {
		$return = array();
		foreach ($arr as $k => $v) {
			if (is_object($v) && self::isModelClass($v)) {
				$return[$k] = $v->dataToArray($hide_ids);
			} elseif (is_object($v) && get_class($v) == 'modelArrayObject') {
				$return[$k] = self::dataToArraySubQuery($v, $hide_ids);
			} else {
				if (is_object($v)) $v = (array) $v;
				$is_id = (substr($k, -3) == '_id');
				if (!$is_id || !$hide_ids) {
					$return[$k] = $v;
				}
			}
		}
		unset($arr);
		return $return;
	}

/**

	@function	delete
	@return		(array) either a success or fail status array
	@param		(null)

**/

	public function delete() {
		
		$id = $this->getID();

		if ($this->_token != Model::generateToken($id, $this->_primary_table) || !$this->_token) {
			$this->_errors[] = 'You do not have permission to remove this record.';
		}

		if (!$id) {
			$this->_errors[] = 'Identifier is not set, there is nothing to delete.';
		}

		$o = $this;
		$return_errors = function() use($o) {
			return array(
				'status' => 'Error',
				'errors' => $o->_errors,
				'data' => $o->dataToArray(true)
			);
		};

		if ($this->_errors) {
			return $return_errors();
		}
		
		$now = aql::now();
		
		$fields = array(
			'active' => 0,
			'mod_time' => $now,
			'update_time' => $now
		);

		if (defined('PERSON_ID') && PERSON_ID) {
			$fields['mod__person_id'] = $fields['update__person_id'] = PERSON_ID;
		}

		if ($this->methodExists('before_delete')) {
			$this->before_delete();
		}

		if (aql::update($this->_primary_table, $fields, $id)) {
			
			// clears the memcache of stored objects of this identifier.
			$delete_key = function($m) use($id) {
				$key = sprintf('%s:loadDB:%d', $m, $id);
				mem($key, null);	
			};

			if ($this->_model_name != 'Model') {
				global $model_dependencies;
				$delete_key($this->_model_name);
				if (is_array($model_dependencies[$this->_primary_table])) {
					foreach ($model_dependencies[$this->_primary_table] as $m) {
						$delete_key($m);
					}
				}
			}

			if ($this->methodExists('after_delete')) {
				$this->after_delete();
			}

			return array( 'status' => 'OK' );

		} else {
			$this->_errors[] = 'Error Deleting.';
			return $return_errors();
		}
		
	}

/**

	@function 	failTransaction
	@return		(null)
	@param		(null)

**/
	public function failTransaction() {
		global $dbw;
		$dbw->FailTrans();
	}

/**

	@function 	genericValidation
	@param 		(string) field_name
	@param 		(string) display name, for errors
	@param 		(string) value of field,
	@param 		(string) validation function to use, in validation class
	@param 		(bool) replace the value, default is false

**/
	public function genericValidation($field, $name, $val, $fn, $replace = false) {
		if (!class_exists('validation')) {
			$this->_errors[] = 'Cannot use this validation features without the <strong>Validation</strong> class. It is in the CMS codebase.';
			return;
		}
		if (!$field || !$name) return;
		if (!is_callable('validation', $fn)) return;
		if (!$val) return true;
		$valid = validation::$fn($val);
		if (!$valid) {
			$this->_errors[] = "{$name} is invalid.";
			return false;
		} else if ($replace) {
			$this->_data[$field] = $valid;
			return false;
		}
		return true;
	}

/**

	@function	get
	@return		(model) of that name
	@param		(string)
	
**/

	public static function get($str = null, $id = null, $sub_do_set = false) {
		
		if (!is_string($str)) {
			throw new Exception('Model name or AQL must be specified when using Model::get()');
		}

		# get class if it exists
		aql::include_class_by_name($str);
		return (class_exists($str))
			? new $str($id, null, $sub_do_set)
			: new model($id, $str);

	}

/**
	
	@function 	refreshCache
	@return 	(model) object
	@param 		(identifier)

	Does not check the cache for the object, reads directly from DB, and writes to cache.

**/

	public static function refreshCache($id) {
		$class = get_called_class();
		
		if ($class == 'Model') {
			throw new Exception('Model::refreshCache needs to be called on a subclass');
		}

		return new $class($id, null, true);
	}

/**
	@function  	getPartial
	@return    	model object
	@param 		identifier (ID/IDE)
	@param 		(array) key value pairs 
		example:
			if the model is:
				artist {
					... fields
					[artist_album]s,
					[artist_genre]s,
					[artist_label]
				}
			php:
			$o = artist::getPartial($id, array(
				'artist_label' => true,
				'artist_album' => array(
					'artist_album_label' => true
				)
			));
**/
	public static function getPartial($id = null, $refresh = array()) {
		$cl = get_called_class();
		
		$o = new $cl($id, null, false, array(
			'refresh_sub_models' => false
		));

		if (is_array($refresh)) foreach ($refresh as $k => $v) {
			if (!$o->isObjectParam($k)) continue;
			if ($o->isPluralObject($k)) {
				foreach ($o->{$k} as $key => $sub) {
					$class = get_class($sub);
					$o->$k[$key] = $class::getPartial($sub->getID(), $v);
				}
			} else {
				$class = get_class($o->$k);
				$o->$k = $class::getPartial($o->$k->getID(), $v);
			}
		}

		return $o;

	}

/**

	@function	getActualObjectName
	@return		(string)
	@param		(string)

**/

	public function getActualObjectName($str) {
		if (!$this->isObjectParam($str)) return null;
		foreach ($this->getStoredAqlArray() as $table) {
			if ($table['objects'][$str]) {
				return $table['objects'][$str]['model'];
			}
		}
		return null;
	}

	public static function getAQL() {
		$c = get_called_class();
		return self::_getAql($c);
	}

/**
	
	@function	_getAql
	@return		(model)
	@param		(string) -- aql, or model name, or null

**/

	public function _getModelAql($aql = null) {
		if ($this->getStoredAql()) return $this;
		if (!$aql) { $this->_getAql($this->_model_name); } 
		else if (aql::is_aql($aql)) { $this->_aql = $aql; $this->_aql_set_in_constructor = true; } 
		else { $this->_model_name = $aql; $this->_getAql($this->_model_name); }
		return $this;
	}

	public function getStoredAql() {
		return if_not(aql2array::$aqls[$this->_model_name], $this->_aql);
	}

	public function getStoredAqlArray() {
		return if_not(aql2array::$aqlArrays[$this->_model_name], $this->_aql_array);
	}

	public function _getAql($model_name) {
		return if_not(aql2array::$aqls[$model_name], function() use($model_name) {
			return aql2array::$aqls[$model_name] = aql::get_aql($model_name);
		});
	}

	public static function getByClause($clause, $model_name = null) {
		$model_name = ($model_name) ? $model_name : self::getCalledClass();
		if (!$model_name || $model_name == 'mMdel') {
			throw new Exception('Model::getByClause expects a second parameter of model_name');
		}
		if (!$clause['where']) {
			throw new Exception('Model::getByClause expects a second parameter of model_name');
		}
		$rs = aql::select(aql::get_min_aql_from_model($model_name), $clause);
		foreach ($rs as $k => $v) {
			$rs[$k] = new $model_name($v['id']);
		}
		if ($clause['limit'] == 1) return $rs[0];
		return $rs;
	}

	public static function getList($clause = array(), $do_count = false) {
		$model_name = self::getCalledClass();
		if (!$model_name || $model_name == 'Model') {
			throw new Exception("Model::getList expects a clause array as a parameter.");
			return;
		}
		$sql = aql::sql(aql::get_aql($model_name), $clause);
		if ($do_count) {
			$r = sql($sql['sql_count']);
			return $r->Fields('count');
		} else {
			$ids = array();
			$r = sql($sql['sql_list']);
			while (!$r->EOF) {
				$ids[] = $r->Fields('id');
				$r->moveNext();
			}
			return $ids;
		}

	}

	public function getToken($id = null, $primary_table = null) {
		$primary_table = ($primary_table) ?: $this->getPrimaryTable();
		if ($id && !is_numeric($id)) $id = decrypt($id, $primary_table);
		$id = ($id) ?: $this->getID();
		return self::_makeToken($id, $primary_table);
	}

	public static function generateToken($id = null, $primary_table = null) {
		
		if (!$primary_table) {
			$cl =  get_called_class();
			$o = new $cl;
			return $o->getToken($id);
		}

		if ($id && !$is_numeric($id)) $id = decrypt($id, $primary_table);
		return self::_makeToken($id, $primary_table);
	}

	private static function _makeToken($id, $table) {
		if (!$id || !$table) return null;
		return encrypt($id, encrypt($id, $table));
	}

	public function getCalledClass() {
		if (!self::isStaticCall()) {
			return get_class($this);
		}
		if (function_exists('get_called_class')) {
			return get_called_class();
		}
		else return null;
	}


/**

	@function	getAqlArray
	@return		(array)
	@param		(null)

**/

	public function getAqlArray() {
		return $this->getStoredAqlArray();
	}

/**

	@function 	getModel
	@return		(string)
	@param		(null)

**/

	public function getModel() {
		return $this->getStoredAql();
	}

	public function getModelName() {
		return (get_class($this) == 'Model')
			? $this->getStoredAqlArray()
			: $this->_model_name;
	}

	public function getPrimaryTable() {
		return $this->_primary_table;
	}

/**
 
 	@function	getProperties
 	@return		(array)
 	@param		(null)

**/
	public function getProperties() {
		return array_keys($this->_properties);
	}

/**
 
 	@function	isModelClass
 	@return		(bool)
 	@param		(mixed) class instance

**/
	public static function isModelClass($class) {
		return (is_a($class, 'Model'));
	}

/**

	@function	isObjectParam
	@return		(bool)
	@param		(string)

**/

	public function isObjectParam($str) {
		if (array_key_exists($str, $this->_objects)) return true;
		else return false;
	}

	public function isPluralObject($str) {
		if (!$this->isObjectParam($str)) return false;
		return ($this->_objects[$str] === 'plural');
	}

	public function isSingleObject($str) {
		if (!$this->objectParam($str)) return false;
		return (!$this->isPluralObject($str));
	}

/**

	@function 	loadArray
	@return		(model)
	@param		(array) -- data array in the proper format

**/

	public function loadArray( $array = array()) {
		if (!$array) $array = $_POST;
		if (is_array($array)) foreach ($array as $k => $v) {
			if ($k == '_token') {
				$this->{$k} = $v;
			} else if ($this->propertyExists($k) || preg_match('/(_|\b)id(e)*?$/', $k)) {
				if ($this->isObjectParam($k)) { 
					$obj = $this->getActualObjectName($k);
					aql::include_class_by_name($obj);
					if ($this->_objects[$k] === 'plural') {
						foreach ($v as $key => $arr) {
							if (is_array($arr)) {
								if (class_exists($obj))
									$this->_data[$k][$key] = new $obj();
								else
									$this->_data[$k][$key] = new model(null, $obj);
								$this->_data[$k][$key]->loadArray($arr);
							} else {
								$this->_data[$k][$key] = $arr;
							}
						}
						$this->_data[$k] = new modelArrayObject($this->_data[$k]);
					} else {
						if (is_array($v)) {
							if (class_exists($obj))
								$this->_data[$k] = new $obj();
							else
								$this->_data[$k] = new model(null, $obj);
							$this->_data[$k]->loadArray($v);
						} else {
							$this->_data[$k] = $v;
						}
					}
				} else if (is_array($v)) {
					$this->_data[$k] = $this->toArrayObject($v);
				} else {
					if (substr($k, -4) == '_ide') {
						$d = aql::get_decrypt_key($k);
						$decrypted = decrypt($v, $d);
						$field = substr($k, 0, -1);
						$this->_data[$field] = $decrypted;
						$this->_properties[$field] = true;
					}
					$this->_data[$k] = $v;
					if (!$this->propertyExists($k)) $this->_properties[$k] = true;
				}
			} 
		}
		return $this;
	}

	public static function cacheExpired($o) {
		$mod_time = null;
		if (isset($o::$mod_time)) $mod_time = $o::$mod_time;
		if (!$mod_time) return false;
		if ($mod_time && !$o->_cached_time) return true;
		$expires = strtotime($mod_time);
		$cached = strtotime($o->_cached_time);
		$return = $cached <= $expires;
		elapsed('cacheExpired:'.($return?'true':'false'));
		return $return;
	}

/**
 
 	@function	loadDB
 	@return 	(model)
 	@param		(string) identifier

**/
	public function loadDB($id, $do_set = false, $use_dbw = false) {
		
		if (!is_numeric($id)) { $id = decrypt($id, $this->_primary_table); }
		if (!is_numeric($id)) {
			$this->_errors[] = 'AQL Model Error: identifier needs to be an integer or an IDE.';
			return $this;
		}
		
		$mem_key = $this->_model_name.':loadDB:'.$id;
		$reload_subs = false;
		$do_set = ($do_set || $this->_do_set || $_GET['refresh']) ? true : false;
		$is_model_class = ($this->_model_name != 'Model');

		if ($do_set || $use_dbw) { $use_dbw = true; global $dbw; }
		$db_conn = ($use_dbw) ? $dbw : null;

		$that = $this; // for lexical binding with anonymous funcitons.

		$aql_profile = function($mem_key = null) use($that, $db_conn, $id) {
			$o = aql::profile($that->getModelName(), $id, true, $that->_aql, true, $db_conn);
			if ($mem_key)  {
				$o->_cached_time = date('c');
				mem($mem_key, $o);
			}
			return $o;
		};

		if (!$do_set && $is_model_class) { 
			// do a normal get from cache, if it isn't there, put it there.
			$o = mem($mem_key);
			if (!$o->_data || self::cacheExpired($o)) {
				$o = $aql_profile($mem_key);
			} else {
				$reload_subs = true;	
			}
		} else if ($do_set && $is_model_class && !$this->_aql_set_in_constructor) { 
			// refresh was specified, and this isn't a temp model (so we want to store in cache)
			$o = $aql_profile($mem_key);
		} else { // this is a temp model, fetch from db
			$o = $aql_profile();
		}

		if (self::isModelClass($o) && is_array($o->_data)) { 
			// we have a proper object fetched, update the data in $this using $o
			$arr = array('data', 'properties', 'objects');
			array_walk($arr, function($key) use($o, $that) {
				$k = '_' . $key;
				$that->$k = array_merge($that->$k, $o->$k);
			});
			$this->_id = $id;
			$this->_cached_time = $o->_cached_time;
			if ($reload_subs) $this->reloadSubs($use_dbw);
		} else {
			$this->_errors[] = 'No data found for this identifier.';
		}

		return $this;
	}

/**

	@function 	loadIDs
	@return		(null)
	@param		(array) ids, used for save

**/

	public function loadIDs($ids = array()) {
		foreach ($ids as $k => $v) {
			if (!$this->_data[$k] && $this->propertyExists($k)) $this->_data[$k] = $v;
		}
	}

/**
 
 	@function	loadJSON
 	@return		(model)
 	@param		(string)

**/
	public function loadJSON($json) {
		$array = json_decode($json, true);
		if (is_array($array)) return $this->loadArray($array);
		$this->_errors[] = 'ERROR Loading JSON. JSON was not valid.';
		return $this;
	}



	public function makeAqlArray() {
		if ($this->_model_name == 'Model' || !$this->_model_name) {
			$this->_aql_array = aql2array($this->_aql);
		} else {
			self::$_metadata[$this->_model_name]['aql_array'] = &aql2array::get($this->_model_name, $this->getStoredAql());
		}
	}

/**

	@function 	makeFKArray
	@return		(array) 
	@param		(array)

	makes a foreign key array from the aql_array

**/
	public function makeFKArray($aql_array) {
		$fk = array();
		foreach ($aql_array as $k => $v) {
			if (is_array($v['fk'])) foreach ($v['fk'] as $f) {
				$fk[$f][] = $v['table']	;
			}
		}
		return $fk;
	}

/**

	@function 	makeSaveArray (recursive)
	@return		(array) save array
	@param		(array) data array
	@param		(array) aql_array

**/

	public function makeSaveArray($data_array = array(), $aql_array = array()) {
		if (!$data_array && !$aql_array) {
			$data_array = $this->_data;
			$aql_array = $this->getStoredAqlArray();
		}
		$tmp = array();
		if (is_array($data_array)) foreach($data_array as $k => $d) {
			if (!is_object($d) && !$this->isObjectParam($k)) { // this query
				foreach ($aql_array as $table => $info) {
					if ($info['fields'][$k]) {
						$field_name = substr($info['fields'][$k], strpos($info['fields'][$k], '.') + 1);
						if ($tmp[$info['table']]['fields'][$field_name] != 'id') $tmp[$info['table']]['fields'][$field_name] = $d;
						else $tmp[$info['table']]['id'] = $d;
					} else if (substr($k, '-4') == '_ide') {
						if (substr($k, 0, -4) == $info['table']) {
							$tmp[$info['table']]['id'] = decrypt($d, $info['table']);
						}
					} else if (substr($k, '-3') == '_id') {
						$table_name = explode('__', substr($k, 0, -3));
						$table_name = ($table_name[1]) ? $table_name[1] : $table_name[0];
						if ($info['table'] == $table_name && $d !== NULL) {
							$tmp[$info['table']]['id'] = $d;
						}
					}
				}
			} else if ($this->isObjectParam($k)) { // sub objects
				if ($this->_objects[$k] === 'plural') {
					foreach ($d as $i => $v) {
						$tmp['__objects__'][] = array('object' => get_class($v), 'data' => $v->_data);
					}
				} else {
					$tmp['__objects__'][] = array('object' => get_class($d), 'data' => $d->_data);
				}
			} else { // sub queries
				$d = $this->toArray($d);
				foreach ($aql_array as $table => $info) {
					if (is_array($info['subqueries'])) foreach($info['subqueries'] as $sub_k => $sub_v) {
						if ($k == $sub_k) {
							foreach ($d as $i => $s) {
								if (is_object($s) && get_class($s) == 'stdClass') $s = (array) $s;
								$tmp[$info['table']]['subs'][] = $this->makeSaveArray($s, $sub_v);
							}
							break;
						}
					}
				}
			}
		}
		// make sure that the array is in the correct order
		$fk = self::makeFKArray($aql_array);
		unset($aql_array); unset($data_array);
		return self::makeSaveArrayOrder($tmp, $fk);
	}

/**

	@function	makeSaveArrayOrder
	@return		(array) reordered by foreign keys
	@param		(array)	needs reordering
	@param		(array)	foreign keys

**/

	public function makeSaveArrayOrder($save_array, $fk) {
		$return_array = array();
		$first = array(); // prepends to return array
		foreach ($fk as $parent => $subs) {
			foreach ($subs as $dependent) {
				if ($save_array[$dependent]) {
					if (!array_key_exists($dependent, $fk)) {
						$return_array[$dependent] = $save_array[$dependent];
						unset($save_array[$dependent]);
					} else {
						$return_array = array($dependent => $save_array[$dependent]) + $return_array;
						unset($save_array[$dependent]);
					}
				}
			}
		}
		return $save_array + $return_array;
	}

	public function removeIgnores($save_array = array()) {
		if (!$this->_ignore) return $save_array;

		// remove tables
		if (is_array($this->_ignore['tables'])) {
			foreach ($this->_ignore['tables'] as $remove) {
				if (!array_key_exists($remove, $save_array)) continue;
				unset($save_array[$remove]);
			}
		}

		// remove objects
		if (is_array($this->_ignore['objects']) && $save_array['__objects__']) {
			foreach ($this->_ignore['objects'] as $remove) {
				foreach ($save_array['__objects__'] as $k => $v) {
					if ($v['object'] == $remove) {
						unset($save_array['__objects__'][$k]);
					}
				}
			}
		}

		// remove subs
		if (is_array($this->_ignore['subs'])) {
			foreach ($this->_ignore['subs'] as $remove) {
				foreach ($save_array as $i => $k) {
					if (is_array($k['subs'])) foreach ($k['subs'] as $n => $sub) {
						if (array_key_exists($remove, $sub)) {
							unset($save_array[$i]['subs'][$n]);
						} // endif exists
					} // end subs
				} // end tables
			} // end removes
		}

		// remove fields
		if (is_array($this->_ignore['fields'])) {
			foreach ($this->_ignore['fields'] as $remove) {
				foreach($save_array as $k => $v) {
					if (!is_array($v['fields']) || !array_key_exists($remove, $v['fields'])) continue;
					unset($save_array[$k]['fields'][$remove]);
				}
			}
		}
		return $save_array;
	}

/**
 	
 	@function	makeProperties
 	@return		(null)
 	@param		(null)

**/
	public function makeProperties() {
		if ($this->getStoredAql()) {
			$this->makeAqlArray();
			$i = 0;
			foreach ($this->getStoredAqlArray() as $table) {
				if ($i == 0) {
					$this->_primary_table = $table['table'];
					$this->addProperty($this->_primary_table.'_id');
				}
				$this->tableMakeProperties($table);
				$i++;
			}
			unset($i);
		} else {
			if (!is_ajax_request()) {
				throw new Exception('AQL Error: <strong>'.$this->_model_name.'</strong> is not a valid model.');
				return;
			} else {
				exit_json(array(
					'status' => 'Error',
					'errors' => array(
						'AQL Error: <strong>'.$this->_model_name.'</strong> is not a valid model.'
					)
				));
			}
		}
		return $this;
	} // end makeParms

	public function offsetExists($offset) {
		return isset($this->_data[$offset]);
	}

	public function offsetGet($offset) {
		return (isset($this->_data[$offset])) ? $this->_data[$offset] : null;
	}

	public function offsetSet($offset, $value) {
		if (is_array($value)) $value = self::toArrayObject($value);
		$this->$offset = $value;
	}

	public function offsetUnset($offset) {
		unset($this->_data[$offset]);
	}

/**

	@function 	reload
	@return		(null)
	@param		(array)

**/

	public function reload($save_array = null) {
		global $model_dependencies;
		$id = $save_array[$this->_primary_table]['id'];
		if ($id || $this->_id) {
			$this->_id = ($id) ? $id : $this->_id;
			$this->loadDB($this->_id, true, true);
			// reloads models with the same primary table
			if ($this->_primary_table) {
				if (is_array($model_dependencies[$this->_primary_table])) {
					foreach ($model_dependencies[$this->_primary_table] as $m) {
						if ($m == $this->_model_name) continue;
						$o = Model::get($m, $this->_id, true);
					}
				}
			}
		}
		if ($this->methodExists('construct')) $this->construct();
	}

/**
	
	@function	reloadSubs
	@return		(null)

	for when using memcache, if there are sub objects, reload them to make sure they are up do date

**/


	public function reloadSubs($use_dbw = false) {
		if (!$this->_refresh_sub_models) return;
		foreach (array_keys($this->_objects) as $o) {
			if ($this->_objects[$o] === 'plural') {
				foreach ($this->_data[$o] as $k) {
					if (self::isModelClass($k)) {
						$k->_do_set = false;
						$k->loadDB($k->_id, $this->_do_set, $use_dbw);
						if ($k->methodExists('construct')) $k->construct();
					}
				}
			} else if (self::isModelClass($this->_data[$o])) {
				$this->$o->_do_set = false;
				$this->$o->loadDB($this->$o->_id, $this->_do_set, $use_dbw);
				if ($this->$o->methodExists('construct')) $this->$o->construct();
			}
		}
	}	

	public function disableSubReload() {
		$this->_refresh_sub_models = false;
	}

	public function removeProperty() {
		$num_args = func_num_args();
		$args = func_get_args();
		for ($i = 0; $i < $num_args; $i++) {
			unset($this->_properties[$args[$i]]);
		}
		return $this;
	}

	public function saveProperties($arr = array()) {
		if (!$this->{$this->_primary_table.'_id'}) {
			throw new Exception('Model::saveProperties can only used on a model with an identifier.');
			return;
		}
		if (!$arr || !is_array($arr)) {
			throw new Exception('Model::saveProperties expects a non empty array as an argument.');
			return;
		}
        $class = get_called_class();
        $tmp = new $class;
        $tmp->{$this->_primary_table.'_id'} = $this->{$this->_primary_table.'_id'};
        $tmp->loadArray($arr);
        $tmp->_token = $tmp->getToken();
        $re = $tmp->save();
        if ($re['status'] == 'OK') foreach (array_keys($arr) as $k) $this->$k = $tmp->$k;
        return $re;
    }

/** 
	
	@function	save
	@return		(bool)
	@param		(null)

	has hooks each takes the save_array as param
		before_save
		after_save
		after_fail

**/

	public function save($inner = false) {
		
		global $dbw, $db_platform, $aql_error_email, $is_dev;
		if (!$dbw) $this->_errors[] = self::E_READ_ONLY;
		
		if ($inner) {
			$this->_use_token_validation = false;
			$this->_is_inner_save = true;
		}

		$this->validate();

		$aql_arr = $this->getStoredAqlArray();
		if (!$aql_arr) {
			$this->_errors[] = 'Cannot save model without an aql statement.';
		}

		if ($this->_errors) {
			return $this->after_fail();
		} 

		$is_insert = $this->isInsert();
		$is_update = $this->isUpdate();

		if ($is_insert && $this->methodExists('before_insert')) {
			$this->before_insert();
		}

		if ($is_update && $this->methodExists('before_update')) {
			$this->before_update();
		}

		$save_array = $this->makeSaveArray($this->_data, $aql_arr);

		if (!$save_array) {
			if (!$this->_is_inner_save) {
				$this->_errors[] = 'Error generating save array based on the model. There may be no data set.';
				return $this->after_fail();
			} else {
				return;
			} 
		}

		$save_array = $this->removeIgnores($save_array);

		if (!$this->_errors) {

			if ($this->_abort_save) {
				return $this->after_save($save_array);
			}

			if (!$this->_is_inner_save) {
				$dbw->startTrans();
			}
			
			if ($this->methodExists('before_save')) {
				$save_array = $this->before_save($save_array);
			}

			$save_array = $this->saveArray($save_array);
			$transaction_failed = $dbw->HasFailedTrans();

			if (!$this->is_inner_save) {
				$dbw->CompleteTrans();	
			}

			if ($transaction_failed) {
				return $this->_handleSaveFailure($save_array);
			} else {
				return $this->_handleSaveSuccess($save_array, $is_insert, $is_update);
			}

		}
		
	}

	protected function _handleSaveFailure($save_array) {
		global $is_dev;
		
		if (!in_array('Save Failed.', $this->_errors)) {
			$this->_errors[] = 'Save Failed.';
			if ($is_dev) {
				$this->_errors[] = 'Failure in model: ' . $this->_model_name;
				$this->_errors = array_merge($this->_errors, aql::$errors);
			}
		}

		return $this->after_fail($save_array);

	}

	protected function _handleSaveSuccess($save_array, $is_insert = false, $is_update = false) {
		
		if ($this->methodExists('before_reload')) {
			$this->before_reload();
		}

		$this->reload($save_array);

		if ($is_insert && $this->methodExists('after_insert')) {
			$this->after_insert();
		}

		if ($is_update && $this->methodExists('after_update')) {
			$this->after_update();
		}

		return $this->after_save($save_array);

	}

/**

	@function	saveArray (recursive)
	@return		(array)
	@param		(array)
	@param		(array)

**/

	public function saveArray($save_array, $ids = array()) {
		global $is_dev;
		$objects = $save_array['__objects__'];
		unset($save_array['__objects__']);
		foreach ($save_array as $table => $info) {
			foreach ($ids as $n => $v) {
				if (is_array($this->_ignore['fields']) && in_array($n, $this->_ignore['fields'])) continue;
				if (is_array($info['fields']) && !$info['fields'][$n]) {
					$save_array[$table]['fields'][$n] = $v;
					$info['fields'][$n] = $v;
				}
			}
			if (is_numeric($info['id'])) {
				if (is_array($info['fields']) && $info['fields']) {
					if (!$info['fields']['update_time']) $info['fields']['update_time'] = aql::now();
					if (defined('PERSON_ID')) {
						if (!$info['fields']['mod__person_id']) $info['fields']['mod__person_id'] = PERSON_ID;
						if (!$info['fields']['update__person_id']) $info['fields']['update__person_id'] = PERSON_ID;
					}
					aql::update($table, $info['fields'], $info['id'], true);
				}
			} else {
				if (is_array($info['fields']) && $info['fields']) {
					$rs = aql::insert($table, $info['fields'], true);
					if (defined('PERSON_ID') && !$info['fields']['insert__person_id']) $info['fields']['insert__person_id'] = PERSON_ID;
					$save_array[$table]['id'] = $info['id'] = $rs[0][$table.'_id'];
				}
			}
			$ids[$table.'_id'] = $info['id'];
			if (is_array($info['subs'])) foreach ($info['subs'] as $i=>$sub) {
				$save_array[$table]['subs'][$i] = $this->saveArray($sub, $ids);
			}
		}
		if (is_array($objects)) foreach ($objects as $o) {
			if ($o['data']) {
				$tmp = Model::get($o['object']);
				$tmp->_data = $o['data'];
				$tmp->loadIDs($ids);
				$pt = $tmp->_primary_table;
				$pt_id = $pt.'_id';
				if (!$tmp->{$pt_id} && $this->$pt_id) {
					$tmp->$pt_id = $this->$pt_id;
				}
				$return = $tmp->save(true);
				if ($return['status'] != 'OK') {
					if (is_array($return['errors']))
						$this->_errors = $this->_errors + $return['errors'];
					// $this->_errors[] = "Error on Model: '{$o['object']}'";
					$this->failTransaction();
				}
			}
		}
		$save_array['objects'] = $objects;
		return $save_array;
	}

/**
 
 	@function	tableMakeProperties
 	@return		(null)
 	@param		(array)
 	@param		(bool)

**/
	public function tableMakeProperties($table, $sub = null) {
		if (is_array($table['objects'])) foreach ($table['objects'] as $k => $v) {
			$this->addProperty($k)->$k = array();
			$this->_objects[$k] = ($v['plural']) ? 'plural' : true;
		}

		if (is_array($table['fields'])) foreach ($table['fields'] as $k => $v) {
			if (preg_match('/[\b_]id$/', $k)) $this->addProperty($k.'e');
			$this->addProperty($k);
		}

		if (is_array($table['subqueries'])) foreach($table['subqueries'] as $k => $v) {
			$this->addProperty($k)->$k = array();
		}

		$this->addProperty($table['table'].'_id');
	}

/**

	@function	toArray
	@return		(array)
	@param		(arrayObject)
**/

	public function toArray($obj) {
		if (is_object($obj) && get_class($obj) == 'ModelArrayObject') 
			$obj = $obj->getArrayCopy();

		if (is_array($obj)) foreach ($obj as $k => $v) {
			$obj[$k] = self::toArray($v);
		}
		return $obj;
	}

/**

	@function 	toArrayObject
	@return		(arrayObject)
	@param		(array)

**/

	public function toArrayObject($arr = array()) {
		$arr = new modelArrayObject($arr);
		foreach ($arr as $k => $v) {
			$arr[$k] = (is_array($v)) ? self::toArrayObject($v) : $v;
		}
		return $arr;
	}

/**
	
	@function	validate
	@return		(null)
	@param		(bool) skips token validation if true // used internally by the save function

**/

	public function validate() {
		if ($this->methodExists('preValidate')) $this->preValidate();
		$update = ( $this->{$this->_primary_table.'_id'} ) ? true : false;
		if ($update && $this->_use_token_validation) {		
			$token = $this->getToken();
			if ($token != $this->_token || !$this->_token) {
				$this->_return[] = array('token' => $this->_token);
				$this->_errors[] = 'You do not have permission to update this record.';
				return $this;
			}
		}
		foreach (array_keys($this->_properties) as $prop) {
			$isset = true;
			$data_was_set = $this->fieldIsSet($prop);
			$is_required = $this->fieldIsRequired($prop);
			if ($is_required) {
				$n = ($this->_required_fields[$prop]) ? $this->_required_fields[$prop] : $prop;
				$isset = ( !$update || $data_was_set) ? $this->requiredField($n, $this->{$prop}) : false;
			}
			if ($isset && $this->fieldHasValidation($prop) && $data_was_set) {
				$this->{'set_'.$prop}($this->{$prop});
			}
		}
		if (!$this->_errors && $this->methodExists('postValidate')) $this->postValidate();
		return $this;
	}

/**

	@function	printData
	@return		(null)
	@param		(null)

**/

	public function printData() {
		print_pre($this->_data);
	}

/**
 
 	@function	printErrors
 	@return		(null)
 	@param		(null)

**/

	public function printErrors() {
		print_pre($this->_errors);
	}

/**

	@function	propertyExists
	@return		(bool)
	@param		(string)

**/

	public function propertyExists($p) {
		if (array_key_exists($p, $this->_properties)) return true;
		else return false;
	}

/**

	@function 	returnJSON
	@return		(string) 
	@param		(array)

	encodes the array and dies the content with JSON headers

**/

	public static function returnJSON($arr = array()) {
		return json_encode($arr);
	}

/**
	
	@function	returnDataArray
	@return		(array)
	@param		(null)

**/
	
	public function returnDataArray() {
		return $this->_data;
	}

/**
	
	@function 	requiredField
	@return		(bool)
	@param		(string)
	@param		(string)

**/

	public function requiredField($name, $val) {
		if (!$val) {
			$this->_errors[] = "{$name} is required.";
			return false;
		} else {
			return true;
		}
	}

	public function fieldIsRequired($field_name) {
		return array_key_exists($field_name, $this->_required_fields);
	}

	public function fieldIsSet($field_name) {
		return array_key_exists($field_name, $this->_data);
	}

	public function fieldHasValidation($field_name) {
		$method_name = 'set_' . $field_name;
		return $this->methodExists($method_name);
	}

	public function isInsert() {
		return (!$this->{$this->_primary_table.'_id'});
	}

	public function isUpdate() {
		return (!$this->isInsert());
	}

/**
	@function validEmail
	@return   (bool)
	@param    (string)
	@param    (string)
**/

	public function validEmail($val) {
		$val = trim($val);
		if (!filter_var($val, FILTER_VALIDATE_EMAIL)) {
			$this->_errors[] = "{$val} is not a valid email address.";
			return false;
		}
		return true;
	}

	public function isStaticCall() {
		if (!isset($this) && !self::isModelClass($this)) return true;
		$bt = debug_backtrace();
		return (!is_a($this, $bt[1]['class']));
	}

	private function setConfig($sets = array()) {
		if (!$sets) return $this;
		$re = new ReflectionClass($this);
		$props = $re->getProperties(ReflectionProperty::IS_PROTECTED);
		foreach ($props as $prop) {
			$prop_name = $prop->getName();
			$key = substr($prop_name, 1);
			if (!array_key_exists($key, $sets)) continue;
			$this->{$prop_name} = $sets[$key];
			unset($sets[$key]);
		}
		return $this;
	} 

}